package jss.parkinggarageapp;

import filemanager.*;
import java.io.*;
import java.util.*;



/**
 * This class is used to create the graphical user interface for the Garage Point
 * of Sale system. 
 * @author Jamie Studzinski
 * @version 1.0
 */

public class MainWindowGUI extends javax.swing.JFrame {
    private String filePath = "src" + File.separatorChar + "file.txt";
    private Vector<FeeCalculatorStrategy> feeCalc = new Vector<FeeCalculatorStrategy>();
    private List<LinkedHashMap<String, String>> carFees = new ArrayList<LinkedHashMap<String, String>>();
    private AutomatedTeller atm;
    
    private FileReaderStrategy reader = new TextFileReader(new CustomGarageFileFormat(),filePath);
    private FileWriterStrategy writer = new TextFileWriter(new CustomGarageFileFormat(), filePath);
    private FileService fs = new FileService(writer, reader);

    /**
     * Creates new form ParkingGarageGUI
     */
    public MainWindowGUI() {
        FeeCalculatorStrategy thirfty = new ThriftyFeeCalculator(1.5, 2, .75, "A1234");
        FeeCalculatorStrategy bestValue = new BestValueFeeCalculator(2, 3, .5, 10, "B7899");
        feeCalc.add(thirfty);
        feeCalc.add(bestValue);

        initComponents();

        Garage garage = new Garage((FeeCalculatorStrategy) comboBoxFeeCalc.getSelectedItem(), "Jims Parking Garage", "1234 West Ave, Pewaukee, WI");
        atm = new AutomatedTeller(new Receipt(garage), new ReceiptGUIOutput(), garage);
        
        try {
            carFees = fs.getAllData();
        } catch (IOException ex) {
            System.out.println("Error reading in file");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxFeeCalc = new javax.swing.JComboBox(feeCalc);
        lblFeeCalc = new javax.swing.JLabel();
        lblHours = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        btnCalcFee = new javax.swing.JButton();
        lblVehcileID = new javax.swing.JLabel();
        txtVehicleID = new javax.swing.JTextField();
        btnDailyTotal = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFeeCalc.setText("Select Fee Calculator:");

        lblHours.setText("Enter Hours Parked:");

        btnCalcFee.setText("Checkout");
        btnCalcFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcFeeActionPerformed(evt);
            }
        });

        lblVehcileID.setText("Enter Vehicle ID:");

        txtVehicleID.setToolTipText("");

        btnDailyTotal.setText("Garage Daily Total");
        btnDailyTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyTotalActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFeeCalc)
                            .addComponent(lblHours)
                            .addComponent(lblVehcileID))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboBoxFeeCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtHours)
                                    .addGap(135, 135, 135)))
                            .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcFee)
                                .addGap(35, 35, 35)
                                .addComponent(btnDailyTotal)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFeeCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeeCalc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehcileID)
                    .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcFee)
                    .addComponent(btnDailyTotal))
                .addGap(25, 25, 25)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt Action is triggered when the user hits Checkout
     */
    private void btnCalcFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcFeeActionPerformed
        FeeCalculatorStrategy calculateFee = (FeeCalculatorStrategy) comboBoxFeeCalc.getSelectedItem();
        LinkedHashMap<String, String> parkedCar = new LinkedHashMap<String, String>();

        String vehicleID = txtVehicleID.getText();
        double fees = calculateFee.calculateFee(Double.parseDouble(txtHours.getText()));

        parkedCar.put("Hours", txtHours.getText());
        parkedCar.put("Fees", Double.toString(fees));
                

        atm.parkNewVehicle(vehicleID, Double.parseDouble(txtHours.getText()), carFees.size() + 1);
        atm.outputFee(vehicleID);

        carFees.add(carFees.size(), parkedCar);

        
        try {
            fs.getWriter().writeToFile(carFees);
        } catch (IOException ex) {
            System.out.println("Empty File");
        }

    }//GEN-LAST:event_btnCalcFeeActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnDailyTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyTotalActionPerformed

        try {
            carFees = fs.getAllData();
        } catch (IOException ex) {
            System.out.println("Error reading in file");
        }

        atm.outputDailyTotal(carFees);
    }//GEN-LAST:event_btnDailyTotalActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcFee;
    private javax.swing.JButton btnDailyTotal;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox comboBoxFeeCalc;
    private javax.swing.JLabel lblFeeCalc;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblVehcileID;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtVehicleID;
    // End of variables declaration//GEN-END:variables

}
